config/routes.rb
Rails.application.routes.draw do  
<<<<<<< HEAD
  devise_for :users
  root "posts#index"
  
  resources :posts do 
	  	member do
      put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  	resources :comments
  end
  #get 'pages/about'

get '/about', :to => 'pages#about'  
=======
  root "posts#index"
  resources :posts
>>>>>>> origin/master
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
<<<<<<< HEAD
      acts_as_votable
      belongs_to :user
      has_many :comments ,dependent: :destroy
	

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
      


=======
>>>>>>> origin/master
	 validates :title, presence: true,
                    length: { minimum: 5 }
	validates :body, presence: true	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         

        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	 def create
	 	@post = Post.find(params[:post_id])
       
	 	@comment = @post.comments.create(comment_params)
	 	 @comment.user = current_user
	  if @comment.save

	 	redirect_to post_path(@post)

	 end
	end

	 def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		
		
		
		@comment.destroy

		redirect_to post_path(@post)
	
	 end

	 private
	  def comment_params
        params.require(:comment).permit(:name , :body, :user_id, :post_id,:firstname)
	  end
  
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 
 def about

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
<<<<<<< HEAD

  before_action :authenticate_user!, except: [:index , :show]
  


=======
>>>>>>> origin/master
  def index
    @posts =Post.all.order('created_at DESC ')
  end

  def create
<<<<<<< HEAD
    @post = current_user.posts.build(post_params)
         
      if @post.save
        
=======
    @post = Post.new(post_params)
      if @post.save
>>>>>>> origin/master
      redirect_to @post
    else
      render 'new'
      end
  end

<<<<<<< HEAD
  def new 

   @post = Post.new 
=======
  def new
   @post = Post.new
>>>>>>> origin/master

  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
<<<<<<< HEAD
    @post = Post.find(params[:id])
    @post.destroy
 
    redirect_to posts_path
  end

  def edit

    @post = Post.find(params[:id])

  end


  def update

   @post = Post.find(params[:id])

     if @post.update(post_params)
         redirect_to @post
    else
      render 'edit'
    end

  end
  
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_back(fallback_location: root_path)
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_back(fallback_location: root_path)
  end
  
=======
  end

  def edit
  end
>>>>>>> origin/master


   private 
    def post_params
<<<<<<< HEAD
      params.require(:post).permit(:title,:body,:image,:firstname)
=======
      params.require(:post).permit(:title,:body)
>>>>>>> origin/master
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago by <%= comment.user.email %></p>
	
	<%  if comment.user == current_user %>
	
		<div class="btn-group pull-right">
		   <p><%= link_to 'Delete', [comment.post, comment],
										  method: :delete,
										  class: "button",
										 	data: { confirm: 'Are you sure?' } %></p>
	<%end%>
	
	    </div>

	</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<<<<<<< HEAD
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo .png" %>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://twitter.com">Twitter</a></li>
			<li><a href="http://instagram.com">Instagram</a></li>
			<li><a href="https://github.com">Github</a></li>
		</ul>

		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
		<% end %>
	</div>

	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>

			<% if user_signed_in? %>
				<div class="buttons">
					<button class="button"><%= link_to "New Post", new_post_path %></button>
					<button class="button"><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></button>
				</div>
			<% end %>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>
=======
  <!DOCTYPE html>
  <html>
    <head>
      <title>Blogapp</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Releway:400,700' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
    <div id="sidebar">
      <div id="logo">
        <%=link_to root_path do %>
        <%= image_tag "logo .png"%>
         <%end%>
      </div>
  <ul>
  	<li class="category">website</li>
  	<li><%= link_to"Blogapp",root_path%></li>
  	<li>About</li>
      <li class="category">social</li>
      <li> <a href="https://www.twitter.com">Twitter</a></li>
      <li> <a href="https://www.google.com">Google</a></li>
      <li><a href="https://www.instagram.com">Instagram</a></li>
      <li><a href="https://www.Linkdin.com">Linkdin</a></li>
      <li> <a href="https://www.Email.com">Email</a></li>
  </ul>
  <p class="sign_in">AdminLogin </p>
  </div>
  

    <div id="main_content">
       <div id="header">
           
        <div class="button"><p>Allpost</p>
          <button class="button"><%=link_to"newpost",new_post_path%></button>
          <button class="button">Logout</button>
        </div>
      <%flash.each do |name,msg|%>
       <%end%>
    </div>
   <%=yield %>

    </body>
  </html>
>>>>>>> origin/master

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "logo .png" %>
	</div>

	<div id="content">
		<h1>Hey, I'm Rajesh</h1>
		<p>Welcome to week 2 of my 12 Web Apps in 12 Weeks Challenge.</p>
		<p>This week I built a blog in Rails 4. You're actually on the demo application right now. Cool stuff, right!.</p>
		<p>If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter </p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post , html: { multipart: true } do |f|%>

  <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@post.errors.count, "error") %> prohibited
          this post from being saved:
        </h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
     
     <p>
      <%=f.label :image %><br>
      <%=f.file_field :image%>
    </p>
  	<p>
  		<%=f.label :title %><br>
  		<%=f.text_field :title%>
  	</p>

  	<p>
  		<%=f.label :body%><br>
  		<%=f.text_area :body%>
  	</p>
  	<p>
  		<%=f.submit %>
  	</p>
<%end%>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<<<<<<< HEAD
<h1>Edit</h1>
<%=render "form"%>


<%= link_to 'Cancel', posts_path ,class: "button" %>
=======
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>
>>>>>>> origin/master

app/views/posts/index.html.erb
<<<<<<< HEAD
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<%= link_to (image_tag post.image.url(:thumb)),post%>
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y")%> </p>
		<p>

			<h3><%= post.user.email%></h3>
		</p>






      <div class="btn-group">
          <%= link_to like_post_path(post), method: :put, class: "btn btn-primary btn-sm" do %>
        <i class="fa fa-thumbs-up" aria-hidden="true"></i>
        Like	
        <%= post.get_likes.size %>
      <% end %>
      <%= link_to dislike_post_path(post), method: :put, class: "btn btn-danger btn-sm" do %>
        <i class="fa fa-thumbs-down" aria-hidden="true"></i>
       Dislike
        <%= post.get_dislikes.size %>
      <% end %>
 
	</div>
 </div>
<% end %>
=======

<% @posts.each do |post| %>
<div class="post_wrapper">
<h2 class="title"><%= link_to post.title,post%></h2>
<p class="date"><%=post.created_at.strftime("%B,%d,%Y")%></p>

</div>
<%end%>
>>>>>>> origin/master

app/views/posts/new.html.erb
<h1>New post</h1>
<<<<<<< HEAD
<%=render "form"%>

=======
<%= form_for @post   do |f|%>

<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<p>
		<%=f.label :title %><br>
		<%=f.text_field :title%>
	</p>
	<p>
		<%=f.label :body%><br>
		<%=f.text_area :body%>
	</p>
	<p>
		<%=f.submit "create post"%>
	</p>
<%end%>
>>>>>>> origin/master

app/views/posts/show.html.erb
<<<<<<< HEAD
<div class="col-md-12">
<%= image_tag@post.image.url(:medium)%>
<h1 class="title">
<%= @post.title %>
</h1>
<p class="date">
Submitted <%= time_ago_in_words(@post.created_at)%>Ago  <%=@post.user.email%>
=======


<h1 class="title">
<%= @post.title%></h1>



<p class="date">
Submitted<%= time_ago_in_words(@post.created_at)%>Ago
>>>>>>> origin/master
</p>
<p>
<%=@post.body%>
</p>

<<<<<<< HEAD
</div> 
<div class="col-md-9">
<div id="comments">

	<h2><%= @post.comments.count %> Comments</h2>
	
		<%= render @post.comments %>
   
   <% if user_signed_in? %>
	
	<h3>Add a comment:</h3>
	    <%= render "comments/form" %>
    </div>
 <br>

 <% if @post.user == current_user %>
   <%= link_to 'Edit', edit_post_path(@post) , class: "button"%> | <%= link_to 'Destroy', post_path(@post), class: "button",
          method: :delete,
          data: { confirm: 'Are you sure?' } %> | <%=link_to "Back",root_path , class: "button"%>	
  <%end%>
  <%end%>
</div>
=======
<%=link_to "Back",root_path%>
>>>>>>> origin/master